
language: generic

services:
  - docker

stages:
  - compile
  - test

env:
  - IMAGENAME: "stanfordpl/stoke-test:$TRAVIS_BUILD_ID"

jobs:
  include:
    - stage: compile
      script: 
        - echo "$DOCKER_DEPLOY_PWD" | docker login -u "$DOCKER_DEPLOY_USR" --password-stdin
        - docker build --build-arg TRAVIS=1 -t stoke .
        - docker images
        - docker tag stoke "$IMAGENAME"
        - docker push "$IMAGENAME"
    - stage: test
      script: 
        - docker pull "$IMAGENAME"
        - docker run "$IMAGENAME" /bin/sh -c "cd /home/stoke/stoke; make;"
        - docker run "$IMAGENAME" /bin/sh -c "cd /home/stoke/stoke; make test;"

