
language: generic

services:
  - docker

stages:
  - compile
  - test

jobs:
  include:
    - stage: compile
      script: docker build -t bchurchill/stoke .
    - state: test
      script: docker run bchurchill/stoke /bin/sh -c "cd /home/stoke/stoke; make test;"

