
language: generic

services:
  - docker

stages:
  - compile
  - test

jobs:
  include:
    - stage: compile
      script: 
        - echo "$DOCKER_DEPLOY_PWD" | docker login -u "$DOCKER_DEPLOY_USR" --password-stdin
        - docker build --build-arg TRAVIS=1 -t stoke .
        - docker images
        - docker tag stoke "stanfordpl/stoke-test:$TRAVIS_BUILD_ID"
        - docker push "stanfordpl/stoke-test:$TRAVIS_BUILD_ID"
    - stage: test
      script: 
        - docker pull "stanfordpl/stoke-test:$TRAVIS_BUILD_ID"
        - docker run "stanfordpl/stoke-test:$TRAVIS_BUILD_ID" /bin/sh -c "cd /home/stoke/stoke; make;"
        - docker run "stanfordpl/stoke-test:$TRAVIS_BUILD_ID" /bin/sh -c "cd /home/stoke/stoke; make test;"

