
language: generic

services:
  - docker

stages:
  - compile
  - test

env:
  - IMAGENAME: "stanfordpl/stoke-test:$TRAVIS_BUILD_ID"

jobs:
  include:
    - stage: test
      script: 
        - echo "$DOCKER_DEPLOY_PWD" | docker login -u "$DOCKER_DEPLOY_USR" --password-stdin
        - docker build -t stoke .
        - docker run stoke /bin/sh -c "cd /home/stoke/stoke; make test;"
        - docker tag stoke "$IMAGENAME"
        - docker push "$IMAGENAME"

